plugins {
    id 'application'
    id 'java'
    id 'org.openjfx.javafxplugin' version "${javafx_plugins_version}"
    id 'com.diffplug.spotless' version '7.0.1' apply false
}

application {
    mainClass = "${group_id}.${start_class}"
}

dependencies {
    implementation project(':ui')
}

apply from: 'gradle/allProjects.gradle'
apply from: 'gradle/tasks.gradle'
