plugins {
    id 'application'
    id 'java'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

allprojects {
    repositories {
        mavenCentral()
    }
}


application {
    mainClass = start_class
}

dependencies {
    implementation project(':ui')
}

javafx {
    version = javafx_version
    modules = javafx_modules.split(',')
}

dependencies {
    implementation project(':ui')

    implementation "org.openjfx:javafx-controls:${javafx_dependency_version}"
    implementation "org.openjfx:javafx-fxml:${javafx_dependency_version}"

}
