# General
version=0.0.1-SNAPSHOT
java_version=21

# JavaFX
javafx_version=21.0.5
javafx_modules= javafx.web,javafx.swing
javafx_dependency_version=23
javafx_plugins_version=0.1.0

# Junit
junit_jupiter_version=5.11.3
junit_platform_version=1.11.3

# Project
start_class=UIController
group_id=com.mealam.bluenode


