# General
project_name=BlueNode
version=0.0.1-SNAPSHOT
java_version=21
# Project
start_class=UIController
group_id=com.mealam.bluenode
# Dependencies
# JavaFX
javafx_version=21.0.5
javafx_modules=javafx.web,javafx.swing,javafx.media,javafx.fxml,javafx.controls,javafx.graphics,javafx.base
javafx_dependency_version=23
javafx_plugins_version=0.1.0
# Junit
junit_jupiter_version=5.11.3
junit_platform_version=1.11.3
# Else
controlsfx_version=11.1.0
gson_version=2.11.0
guava_version=33.4.0-jre
commons_io_version=2.18.0
commons_lang3_version=3.17.0
httpclient5_version=5.4.1
slf4j_version=2.0.16
logback_version=1.5.16
msg_version=0.9.9



