name: Enhancement Template
description: Create a Enhancement!
title: "[Enhancement]: "
labels: ["Enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for making a Suggestion!
  - type: checkboxes
    attributes:
      label: Rule checks (please read carefully)
      options:
        - label: "I have checked that my issue <a href='https://github.com/MeAlam1/BlueNode/issues' target='_blank'>is not already reported</a>"
          required: true
        - label: "I have checked that my issue <a href='https://github.com/MeAlam1/BlueNode/discussions/9' target='_blank'>is not a known bug</a>"
          required: true
  - type: textarea
    id: what-should-we-add
    attributes:
      label: What do you want to have added?
      description: |
        Please tell us as detailed as possible what you want to have added to BlueNode!
        Feel free to also add Examples if they exist!
    validations:
      required: true
  - type: dropdown
    id: inspiration
    attributes:
      label: Inspiration
      description: Is this idea used in other Applications?
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: input
    id: inspiration-where
    attributes:
      label: Where did you get the inspiration from?
      description: If this idea is used in a different Application, please provide a list of said Applications!
