plugins {
    id 'java'
    id 'org.openjfx.javafxplugin' version "${javafx_plugins_version}"
}

repositories {
    mavenCentral()
}

javafx {
    version = javafx_version
    modules = javafx_modules.split(',').collect { it.trim() }
}

dependencies {
    implementation project(':common')
    implementation project(':utils')

    implementation "org.openjfx:javafx-controls:${javafx_dependency_version}"
    implementation "org.openjfx:javafx-fxml:${javafx_dependency_version}"

}
